spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1111
    username: springuser
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cookbook

security:
  jwt:
    secret-key: thisisaplaceholdernooneshoulduseforproduction